<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ClientsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('clients')->delete();

        \DB::table('clients')->insert([
            0 => [
                'id' => 1,
                'first_name' => 'Rodoolfo',
                'last_name' => 'Alonso',
                'identification_number' => '4344343',
                'email' => 'rodolfito@gmail.com',
                'phone' => '23314134',
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-02-10 19:41:08',
                'updated_at' => '2026-02-10 19:41:08',
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'first_name' => 'Test',
                'last_name' => 'Client',
                'identification_number' => '11111111',
                'email' => null,
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-02-26 19:39:46',
                'updated_at' => '2026-02-26 19:39:46',
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'first_name' => 'TestClient_1772736293706',
                'last_name' => 'User',
                'identification_number' => '12345678',
                'email' => 'test@test.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-05 18:44:54',
                'updated_at' => '2026-03-05 18:44:54',
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'first_name' => 'TestClient_1772822608701',
                'last_name' => 'User',
                'identification_number' => '22608701',
                'email' => 'test_1772822608701@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 18:43:29',
                'updated_at' => '2026-03-06 18:43:29',
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'first_name' => 'TestClient_1772823025250',
                'last_name' => 'User',
                'identification_number' => '23025250',
                'email' => 'test_1772823025250@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 18:50:25',
                'updated_at' => '2026-03-06 18:50:25',
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'first_name' => 'TestClient_1772823249091',
                'last_name' => 'User',
                'identification_number' => '23249091',
                'email' => 'test_1772823249091@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 18:54:09',
                'updated_at' => '2026-03-06 18:54:09',
                'deleted_at' => null,
            ],
            6 => [
                'id' => 7,
                'first_name' => 'TestClient_1772823745588',
                'last_name' => 'User',
                'identification_number' => '23745588',
                'email' => 'test_1772823745588@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 19:02:25',
                'updated_at' => '2026-03-06 19:02:25',
                'deleted_at' => null,
            ],
            7 => [
                'id' => 8,
                'first_name' => 'TestClient_1772823970814',
                'last_name' => 'User',
                'identification_number' => '23970814',
                'email' => 'test_1772823970814@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 19:06:11',
                'updated_at' => '2026-03-06 19:06:11',
                'deleted_at' => null,
            ],
            8 => [
                'id' => 9,
                'first_name' => 'TestClient_1772824385830',
                'last_name' => 'User',
                'identification_number' => '24385830',
                'email' => 'test_1772824385830@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 19:13:06',
                'updated_at' => '2026-03-06 19:13:06',
                'deleted_at' => null,
            ],
            9 => [
                'id' => 10,
                'first_name' => 'TestClient_1772824862368',
                'last_name' => 'User',
                'identification_number' => '24862368',
                'email' => 'test_1772824862368@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 19:21:02',
                'updated_at' => '2026-03-06 19:21:02',
                'deleted_at' => null,
            ],
            10 => [
                'id' => 11,
                'first_name' => 'TestClient_1772825246863',
                'last_name' => 'User',
                'identification_number' => '25246863',
                'email' => 'test_1772825246863@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 19:27:27',
                'updated_at' => '2026-03-06 19:27:27',
                'deleted_at' => null,
            ],
            11 => [
                'id' => 12,
                'first_name' => 'TestClient_1772825515984',
                'last_name' => 'User',
                'identification_number' => '25515984',
                'email' => 'test_1772825515984@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 19:31:56',
                'updated_at' => '2026-03-06 19:31:56',
                'deleted_at' => null,
            ],
            12 => [
                'id' => 13,
                'first_name' => 'TestClient_1772829123507',
                'last_name' => 'User',
                'identification_number' => '29123507',
                'email' => 'test_1772829123507@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 20:32:04',
                'updated_at' => '2026-03-06 20:32:04',
                'deleted_at' => null,
            ],
            13 => [
                'id' => 14,
                'first_name' => 'TestClient_1772829277416',
                'last_name' => 'User',
                'identification_number' => '29277416',
                'email' => 'test_1772829277416@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 20:34:38',
                'updated_at' => '2026-03-06 20:34:38',
                'deleted_at' => null,
            ],
            14 => [
                'id' => 15,
                'first_name' => 'TestClient_1772829304866',
                'last_name' => 'User',
                'identification_number' => '29304866',
                'email' => 'test_1772829304866@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 20:35:05',
                'updated_at' => '2026-03-06 20:35:05',
                'deleted_at' => null,
            ],
            15 => [
                'id' => 16,
                'first_name' => 'TestClient_1772830272444',
                'last_name' => 'User',
                'identification_number' => '30272444',
                'email' => 'test_1772830272444@example.com',
                'phone' => null,
                'address' => null,
                'type' => 'person',
                'status' => 'active',
                'notes' => null,
                'created_at' => '2026-03-06 20:51:12',
                'updated_at' => '2026-03-06 20:51:12',
                'deleted_at' => null,
            ],
        ]);

        // Reset PostgreSQL sequence to max id
        if (\Illuminate\Support\Facades\DB::getDriverName() === 'pgsql') {
            \Illuminate\Support\Facades\DB::statement("SELECT setval(pg_get_serial_sequence('clients', 'id'), COALESCE((SELECT MAX(id) FROM clients), 1))");
        }

    }
}
